theme: minima
title: Shota Matsuo - 松尾 祥汰
url: "https://massssho.github.io"
baseurl: ""
author:
  name: "Shota Matsuo"
header_pages:
  - index.md
  - about.md
  - news.md
  - publications.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
